include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    dead_code: ignore
    duplicate_import: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore ignore
